//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shop_Salon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Polje je obavezno")]
        public string Email { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Polje je obavezno")]
        public string Password { get; set; }
    }
}
