//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shop_Salon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Account()
        {
            this.tbl_Invoice = new HashSet<tbl_Invoice>();
        }
    
        public int Account_Id { get; set; }

        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Korisnicko Ime")]
        [StringLength(50, MinimumLength = 3)]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Password")]
        
        [StringLength(50, MinimumLength = 3)]
        public string Password { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Ime")]
        [StringLength(50, MinimumLength = 2)]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Prezime")]
        [StringLength(50, MinimumLength = 2)]
        public string LastName { get; set; }
        public int Role_Id { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Grad")]
        [StringLength(50, MinimumLength = 2)]
        public string City { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [Display(Name = "Adresa i broj")]
        [StringLength(50, MinimumLength = 3)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Polje je obavezno")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string Email { get; set; }
        public bool Status { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Invoice> tbl_Invoice { get; set; }
    }
}
