//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shop_Salon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Invoice_Detail
    {
        public int Invoice_Id { get; set; }
        public int Product_Id { get; set; }
        public int Quantity { get; set; }
        public int Tax { get; set; }
        public decimal Total_Price_Tax { get; set; }
        public decimal Price_Per { get; set; }
    
        public virtual tbl_Invoice tbl_Invoice { get; set; }
        public virtual tbl_Product tbl_Product { get; set; }
    }
}
